import './globals.css'

export const metadata = {
  title: 'Zayada.io',
  description: 'Generated by Mihnea',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
