
export const metadata = {
  title: 'Zayada.io',
  description: 'Generated by Mihnea',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
